apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}
  namespace: argocd
  labels:
    managed-by: backstage
    owner: ${{ values.owner }}
  annotations:
    backstage.io/source-location: "url:https://github.com/rdurelli/${{ values.name }}"
spec:
  project: default
  source:
    repoURL: https://github.com/rdurelli/${{ values.name }}.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
